infoapp/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',views.contact_view,name='home'),
    path('admin-page/', views.data_list, name='admin-page'),
    path('admin-login/', views.admin_page, name='login'),
    path('edit/<str:pk>/', views.edit_data, name='edit-data'),
    path('delete/<str:pk>/', views.delete_data, name='delete-data'),
    path('logout/',views.user_logout,name='logout'),


]+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

informationWeb/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('infoapp.urls'))
]

infoapp/models.py
from django.db import models

class ContactDatas(models.Model):
    firstname=models.CharField(max_length=20)
    lastname=models.CharField(max_length=10)
    phonenumber=models.BigIntegerField()
    email=models.EmailField()
    message=models.TextField(blank=True)
    create_on=models.DateTimeField(auto_now_add=True)
    update_on=models.DateTimeField(auto_now=True)

    

    class Meta:
        ordering = ['-create_on']
    
    def __str__(self):
        return '{} {}'.format(self.firstname,self.create_on.strftime("%d/%m/%Y"))

infoapp/forms.py
from django import forms
from .models import ContactDatas
class ContactForm(forms.ModelForm):
    class Meta:
        model= ContactDatas
        fields="__all__"


        widgets = {
            'firstname': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Name'}),
            'lastname': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            'phonenumber': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Contact No'}),
            'email': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Role'}),
            'message': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Salary'}),
            
        }

infoapp/views.py
from django.shortcuts import render,redirect
from .forms import ContactForm
from .models import ContactDatas
from django.core.mail import send_mail
from django.conf import settings
from django.db.models import Q
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
import gspread
from oauth2client.service_account import ServiceAccountCredentials


def admin_page(request):
     if request.method == "POST":
        username=request.POST.get('username')
        pass1=request.POST.get('pass')  
        # print(username,pass1)
        user=authenticate(request,username=username,password=pass1)
        if user is not None and user.is_superuser:
            login(request,user)
            return redirect('admin-page')
        else:
            return render(request,'infoapp/admin-login.html',{'error' : 'Incorrect Details!'})
        # print(username,pass1)
     return render(request,'infoapp/admin-login.html')

def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            first = form.cleaned_data['firstname']
            last = form.cleaned_data['lastname']
            phone=form.cleaned_data['phonenumber']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']


            #--------------------------------------------->>>>
            #Google Sheet Append_Data

            scope = ['https://spreadsheets.google.com/feeds', 'https://www.googleapis.com/auth/drive']
            credentials = ServiceAccountCredentials.from_json_keyfile_name('infoapp\key.json', scope)
            gc = gspread.authorize(credentials)
            spreadsheet_name = 'contact_data'
            worksheet_name = 'Sheet1'
            worksheet = gc.open(spreadsheet_name).worksheet(worksheet_name)

            #--------------------------------------------->>>>


            row = [first, last, phone, email, message]
            content= f'Dear {first},\n\nThank you for contacting us. We appreciate your interest and will get back to you as soon as possible.\n\nBest regards,\nGokul.C '
            
            #--------------------------------------------->>>>
            #Send Mail For Replay To User

            send_mail(

                'Thank you for contacting us!',  #Title
                content,                         #Content Of  the Mail 
                'settings.EMAIL_HOST_USER',      #Sender Mail
                [email],                         #Reciver Mail
                fail_silently=False
                )
            #<<<<<<---------------------------------------------

            form.save() #Data Save To Backend 
            worksheet.insert_row(row, index=2) #Data Save To Google Sheet 
            
            return render(request, 'infoapp/main.html',{'message':message})
            
    else:
        form = ContactForm()
    return render(request, 'infoapp/main.html', {'form': form})



@login_required(login_url='login')
def data_list(request):
    search_query = ""
    if request.GET.get('search_query'):
        search_query = request.GET.get('search_query')

    employees = ContactDatas.objects.filter(
        Q(firstname__icontains=search_query) | 
        Q(phonenumber__icontains=search_query) |
        Q(email__icontains=search_query)
    )

    context = {
        'employees': employees,
        'search_query': search_query,
    }
    return render(request, 'infoapp/list.html', context)




def edit_data(request, pk):
    employee = ContactDatas.objects.get(id=pk)
    form = ContactForm(instance=employee)

    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES, instance=employee)
        if form.is_valid():
            form.save()
            return redirect('admin-page')

    context = {
        'employee': employee,
        'form': form,
    }
    return render(request, 'infoapp/edit.html', context)


def delete_data(request, pk):
    employee = ContactDatas.objects.get(id=pk)

    if request.method == 'POST':
        employee.delete()
        return redirect('admin-page')

    context = {
        'employee': employee,
    }
    return render(request, 'infoapp/delete.html', context)


def user_logout(request):
    logout(request)
    return redirect('login')

infoapp/templates/infoapp/admin-login.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Page</title>
    <link rel="stylesheet" href="{% static 'css/admin-page.css' %}">
    <script src="https://kit.fontawesome.com/007022c079.js" crossorigin="anonymous"></script>
</head>
<body>
    <div class="signup-form">
        <div class="container">
          <div class="header">
            <h1>Admin Page</h1>
          </div>
          <form method="POST">
            {% csrf_token %}
            <div class="input">
              <i class="fa-solid fa-user"></i>
              <input type="text" placeholder="Username"  id="username" name="username" autocomplete="off"/>
            </div>
           
            <div class="input">
              <i class="fa-solid fa-lock"></i>
              <input type="password" placeholder="Password" id="pass" name="pass" />
            </div>
            <div class="error">
              {% if error %}
              <p style="color: red;">{{ error }}</p>
              {% endif %}
              </div> 
            <input class="signup-btn" type="submit" value="SIGN UP"  />
            <a href="{% url 'home' %}" class="back-btn" value="" type="button" >Go BACK</a>




          </form>
        
        </div>
      </div>
    
</body>
</html>

infoapp/templates/infoapp/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    
    
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        
        <br><br>
        <div class="alert alert-danger" role="alert">
            Are you sure you want to delete "{{ employee.emp_name }}"?
        </div>
        
        <p>
            <a href="{% url 'admin-page' %}"> <-- Go back</a>
        </p>
        
        <p>
            <input class="btn btn-danger" type="submit" value="Confirm">
        </p>
    </form>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</body> 
</html>

infoapp/templates/infoapp/edit.html

<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit</title>
    <link rel="stylesheet" href="{% static 'css/table.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    

    <div class="container"> 



        
        
        <h1 style="text-align: center; padding-top: 1em; padding-bottom: 1em;">Edit User Information</h1>
        
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-success">
        </form>
    </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        
</body>
</html>

infoapp/templates/infoapp/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User List</title>
    <link rel="stylesheet" href="{% static 'css/table.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    
    
    <h1 style="text-align: center; padding-top: 1em; padding-bottom: 1em;" id="top">Contact Information</h1>
    
    <!-- Search section  -->
    <div class="center-form" style="display: flex; justify-content: center;">
        <form action="{% url 'admin-page' %}" method="GET" style="width: 500px;">
            <div class="input-group mb-3">
                <input type="text" class="form-control" placeholder="Search by  name, email, or mobile" aria-label="" aria-describedby="basic-addon1" style="margin-right: 10px;"
                name="search_query" value="{{ search_query }}"/>
                
                <input class="btn btn-success" type="submit" value="Search"/>
            </div>
            <div class="btns">
                <a href="#bottom-page"><button type="button" class="btn btn-dark">Go to Bottom</button></a>
                <a href= "https://docs.google.com/spreadsheets/d/1ALBHnTriEfSUFcsHu8EZDV-Emf756_B4RrCrisiJjhw/edit?usp=share_link" class="btn btn-success" download >Google Sheeet View</a>
                <a href="{% url 'logout' %}"><button type="button" class="btn btn-danger">Logout</button></a>

            </div>

        </form>
    </div>
    <hr>
    
    <table class="table table-hover table-dark">
        <thead>
            <tr>
                <th scope="col">Firstname</th>
                <th scope="col">Lastname</th>
                <th scope="col">Phonenumber</th>
                <th scope="col">Email</th>
                <th scope="col">Message</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for emp in employees %}
            <tr>
                
                <th scope="row">{{ emp.firstname }}</th>
                <td>{{ emp.lastname }}</td>
                <td>{{ emp.phonenumber }}</td>
                <td>{{ emp.email}}</td>
                <td>{{ emp.message }}</td>
                <td>
                    <a style="margin-right: 30px;" href="{% url 'edit-data' emp.id %}" type="button" class="btn btn-primary">Edit</a>
                    <a href="{% url 'delete-data' emp.id %}" type="button" class="btn btn-danger">Remove</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    
    <div class="text-center" id="bottom-page">
        <a href="#top"><button type="button" class="btn btn-dark">Go to Top</button></a>

        <a href="{% url 'home' %}"><button type="button" class="btn btn-info">Add New Info</button></a>
       <center>
           <a href="{% url 'logout' %}"><button type="button" class="btn btn-danger">Logout</button></a>

       </center> 

    </div>
    <hr>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</body>
</html>

infoapp/templates/infoapp/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}

	<title>Contact Us</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="shortcut icon" href="{% static 'images/web-icon.png' %}" type="png">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	
</head>
<body>
	

	<div class="contact1">
		<div class="container-contact1">
			<div class="contact1-pic js-tilt" data-tilt>
				<span id="submit-icon"style="display:none;" >
					<script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script> 
  				    <lottie-player src="https://lottie.host/e68bdcd8-ba6f-479a-ba88-5f4f944d89fa/DMYPlnMpAY.json" background="transparent" speed=".5" style="width: 500px; height: 500px;" loop autoplay></lottie-player>
				</span>
				<span id="sub-btn">
					<script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script> 
					<lottie-player src="https://lottie.host/0c296bf5-1be3-42a7-bc84-1da0df6230c0/wHU6zS44K0.json" background="transparent" speed=".8" style="width: 600px; height: 600px;" loop autoplay></lottie-player>
					   <center>
						<!-- <div class="admin-btn"> -->
							<a href="{% url 'login' %}" target="blank" class="" type="button">ADMIN LOGIN</a>
						<!-- </div> -->
					</center>
				</span>
				
				

			</div>
			<form class="contact1-form validate-form" id="contact-form" action="{% url 'home' %}" method="post" enctype="multipart/form-data" role="form" onsubmit="return validateForm();" >
				{% csrf_token %}
				<span class="contact1-form-title heading">
					Get in touch
				</span>

				<div class="wrap-input1 validate-input" >
					<input class="input1" type="text" name="firstname" placeholder="FirstName" class="form-control is-invalid"   id="id_firstname" maxlength="20" autocomplete="off" >
					<span class="shadow-input1"></span>
					<span class="error" id="firstNameError"></span>
				</div>

				<div class="wrap-input1 validate-input">
					<input class="input1" type="text" name="lastname" placeholder="Lastname" class="form-control is-invalid"  maxlength="10" id="id_lastname" autocomplete="off">
					<span class="shadow-input1"></span>
					<span class="error" id="lastNameError"></span>
				</div>

				<div class="wrap-input1 validate-input">
					<input class="input1" type="email" name="email" placeholder="Email" class="form-control is-invalid"   id="id_email" autocomplete="off">
					<span class="shadow-input1"></span>
					<span class="error" id="emailError"></span>
				</div>

				<div class="wrap-input1 validate-input">
					<input class="input1 num-int" type="number" control="off" name="phonenumber" placeholder="Phonenumber" class="form-control is-invalid num-btn"    maxlength="10"  id="id_phonenumber"  autocomplete="off">
					<span class="shadow-input1"></span>
					<span class="error" id="phoneNumberError"></span>
				</div>

				

				<div class="wrap-input1 validate-input">
					<textarea class="input1" name="message" id="id_message"  class="form-control is-invalid"  cols="40" rows="10"  autocomplete="off" placeholder="Message"></textarea>
					<span class="shadow-input1"></span>
					<span class="error" id="messageError"></span>
				</div>
				

				<div class="container-contact1-form-btn">
					<button class="contact1-form-btn" type="submit" >
							Submit
					</button>

					<!-- <br> -->

					
				</div>
				<br>
			

			</form>
		</div>
	</div>

	


<script src="{% static 'js/script.js' %}"></script>
</body>
</html>